/**
 * One checklist per tester — LAN-221, Part 3.
 *
 * Generated from the map (Part 1) with the plan's identifiers (Part 2) filled
 * in: for each tester, every workflow that is theirs, as a list of "open this
 * link — you should see this — tick it, or report it". The report form link
 * sits at the top. Not booklets, not prose.
 *
 * Links are computed from the plan before anything is loaded, which is the
 * whole point of deterministic identifiers: the checklist Brian hands out on
 * Monday was written on Friday and resolves on the deployed build.
 */

import { MISSIONS, TESTERS, WORKFLOWS, resolveRoute } from "./map.mjs";

const BOX = "- [ ]";

/** The four checklists, keyed by tester, as Markdown. */
export function renderChecklists({ plan, baseUrl, formUrl, logins = {} }) {
  const out = new Map();
  for (const [testerKey, tester] of Object.entries(TESTERS)) {
    const lines = [];
    lines.push(`# Tester week — ${tester.name}`);
    lines.push("");
    lines.push(
      `**Role:** ${tester.role}. **Sign in at:** ${baseUrl}/login${logins[testerKey] ? ` as ${logins[testerKey]}` : ""}.`,
    );
    lines.push("");
    lines.push(
      `**Report anything that is wrong, missing, confusing or slow here:** ${formUrl ?? "(form link to follow)"}`,
    );
    lines.push("");
    lines.push(
      "Work down the list. Open the link, check what you see against the line, tick it, or report it. Everything is safe to press except sending WhatsApp, which is switched off.",
    );
    lines.push("");
    let n = 0;
    for (const mission of MISSIONS) {
      const mine = WORKFLOWS.filter(
        (workflow) => workflow.tester === testerKey && workflow.mission === mission.id,
      );
      if (mine.length === 0) continue;
      lines.push(`## ${mission.title}`);
      lines.push("");
      for (const workflow of mine) {
        n += 1;
        const later = workflow.arrivesWith
          ? ` _(part of this arrives with ${workflow.arrivesWith}; check what is there today)_`
          : "";
        lines.push(`### ${n}. ${workflow.name}${later}`);
        lines.push("");
        if (workflow.routes.length === 0)
          lines.push(`${BOX} No page of its own. ${workflow.expect}`);
        for (const template of workflow.routes) {
          const { route, missing } = resolveRoute(template, plan.examples);
          if (missing.length > 0) {
            lines.push(
              `${BOX} Open \`${template}\` — no example row for \`${missing.join("`, `")}\` in this load; skip and report if you expected one.`,
            );
            continue;
          }
          lines.push(`${BOX} Open ${baseUrl}${route}`);
        }
        lines.push(`${BOX} You should see: ${workflow.expect}`);
        lines.push("");
      }
    }
    lines.push("---");
    lines.push("");
    lines.push(
      `${n} items. Generated by \`showcase checklists\` for the ${plan.context.anchor} load; every link above resolves to a row that load created.`,
    );
    lines.push("");
    out.set(testerKey, lines.join("\n"));
  }
  return out;
}

/** Which workflows each tester covers, and which nobody does — for the coverage test. */
export function coverage() {
  const covered = new Map(Object.keys(TESTERS).map((key) => [key, []]));
  const uncovered = [];
  for (const workflow of WORKFLOWS) {
    if (workflow.notAWorkflow) continue;
    if (workflow.tester && covered.has(workflow.tester))
      covered.get(workflow.tester).push(workflow.id);
    else uncovered.push(workflow.id);
  }
  return { covered, uncovered };
}
