// @vitest-environment node
/**
 * The diagnostic agents' read-only production identity, proved locally — LAN-435.
 *
 * `scripts/production/agent-readonly.sql` is the paste Brian runs in the
 * production SQL editor. This file runs the same file, unmodified, against the
 * local database and then behaves like an agent through the real
 * `prod:inspect` functions. It proves that PostgreSQL itself — not the tool —
 * refuses every write, every hidden column, every other schema and every
 * self-promotion, and that the visible columns still return rows despite RLS.
 *
 * It cannot prove production is configured this way; the paste's own
 * verification row and the first live run do that. It proves the paste is
 * coherent against this exact schema.
 *
 * Local only: every connection is built from `resolveLocalDatabaseUrl()`. The
 * role is dropped at the end.
 */
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";

import pg from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { resolveLocalDatabaseUrl } from "../scripts/lib/local-db.mjs";
import {
  assertInspectorIdentity,
  columnsQuery,
  ROLE,
  runInspection,
} from "../scripts/diagnostics/prod-inspect.mjs";
import { openLocalClient } from "./helpers/domain-fixture";
import { errorCode } from "./helpers/runtime-role";

const PASTE = readFileSync(
  path.resolve(import.meta.dirname, "../scripts/production/agent-readonly.sql"),
  "utf8",
);
const PASSWORD = randomUUID();
const MARKER_PERSON_ID = randomUUID();

/** The four verification counts the paste ends with. */
interface Verification {
  agent_readonly_password: string;
  unsafe_attributes: string;
  write_privileges: string;
  hidden_columns_readable: string;
  definer_functions_callable: string;
}

let admin: pg.Client;
let agent: pg.Client;

/** Runs the paste as one script, the way the SQL editor does, and returns its last row. */
async function runPaste(): Promise<Verification> {
  const results = (await admin.query(PASTE)) as unknown as pg.QueryResult[];
  return results.at(-1)!.rows[0] as Verification;
}

async function dropRole(): Promise<void> {
  await admin.query(`drop owned by ${ROLE}`).catch(() => undefined);
  await admin.query(`drop role if exists ${ROLE}`).catch(() => undefined);
}

beforeAll(async () => {
  admin = (await openLocalClient()) as unknown as pg.Client;
  await dropRole();

  await admin.query(
    `insert into public.people (id, given_name, family_name, date_of_birth, student_number)
     values ($1, 'LAN-435', 'probe', '2000-01-01', 'S-435')`,
    [MARKER_PERSON_ID],
  );

  // A local, throwaway password; production's is generated by the paste itself.
  await runPaste();
  await admin.query(`alter role ${ROLE} password '${PASSWORD}'`);

  const local = new URL(resolveLocalDatabaseUrl());
  local.username = ROLE;
  local.password = PASSWORD;
  agent = new pg.Client({ connectionString: local.toString() });
  await agent.connect();
}, 30_000);

afterAll(async () => {
  await agent?.end().catch(() => undefined);
  await admin?.query("delete from public.people where id = $1", [MARKER_PERSON_ID]);
  await dropRole();
  await admin?.end();
});

describe("the paste", () => {
  it("reports zero on every safety count, and is safe to run again", async () => {
    const again = await runPaste();

    expect(again).toMatchObject({
      unsafe_attributes: "0",
      write_privileges: "0",
      hidden_columns_readable: "0",
      definer_functions_callable: "0",
    });
    // A re-run to pick up new columns must not rotate the key in .env.local.
    expect(again.agent_readonly_password).toBe("unchanged");
  });

  it("leaves the role able to log in only with the password it already had", async () => {
    const { rows } = await agent.query<{ ok: number }>("select 1 as ok");
    expect(rows[0].ok).toBe(1);
  });
});

describe("what the role can read", () => {
  it("passes the tool's identity check", async () => {
    await expect(assertInspectorIdentity(agent)).resolves.toBeUndefined();
  });

  it("reads rows from RLS-protected tables — the reason it carries bypassrls", async () => {
    const result = await runInspection(agent, {
      text: "select id, given_name, family_name from public.people where id = $1",
      values: [MARKER_PERSON_ID],
    });
    expect(result.rows).toEqual([
      { id: MARKER_PERSON_ID, given_name: "LAN-435", family_name: "probe" },
    ]);
  });

  it("sees what kind of contact a person has, without the value", async () => {
    const result = await runInspection(agent, {
      text: "select kind, is_preferred, scope from public.contact_points limit 1",
    });
    expect(result.rowCount).toBeLessThanOrEqual(1);
  });

  it("lists its own visible columns, without the hidden ones", async () => {
    const result = await runInspection(agent, columnsQuery("people"));
    const visible = String(result.rows[0].visible_columns).split(", ");
    expect(visible).toContain("given_name");
    expect(visible).not.toContain("date_of_birth");
    expect(visible).not.toContain("student_number");
  });
});

describe("what PostgreSQL refuses", () => {
  // Every one of these runs outside the tool's read-only transaction, with the
  // role's read-only default switched off, so the grants alone are on trial.
  beforeAll(async () => {
    await agent.query("set default_transaction_read_only = off");
  });

  it.each([
    ["date of birth", "select date_of_birth from public.people"],
    ["student number", "select student_number from public.people"],
    ["select * on a table with a hidden column", "select * from public.people"],
    ["a contact value", "select normalised_value from public.contact_points"],
    ["an operator's login email", "select login_email from public.operator_accounts"],
    ["emergency contact phone", "select phone from public.person_emergency_contacts"],
    ["agreement form address", "select form_address from public.onboarding_agreements"],
    ["a token hash", "select token_hash from public.rsvp_access_tokens"],
    ["a message's personal links", "select template_variables from public.notification_jobs"],
    ["the sign-up code", "select code from public.recruitment_signup_codes"],
    ["auth users", "select id from auth.users"],
    ["the staging schema", "select id from staging.legacy_roster_rows"],
  ])("refuses to read %s", async (_label, sql) => {
    expect(await errorCode(agent, sql)).toBe("42501");
  });

  it.each([
    ["insert", "insert into public.people (given_name) values ('rogue')"],
    ["update", `update public.people set given_name = 'rogue' where id = '${MARKER_PERSON_ID}'`],
    ["delete", `delete from public.people where id = '${MARKER_PERSON_ID}'`],
    ["truncate", "truncate public.people"],
    ["create table", "create table public.rogue (id int)"],
    ["alter table", "alter table public.people add column rogue text"],
    ["drop table", "drop table public.people"],
    ["create schema", "create schema rogue"],
    ["create function", "create function public.rogue() returns int language sql as 'select 1'"],
    ["grant itself more", "grant insert on public.people to agent_readonly"],
    ["promote itself", "alter role agent_readonly createrole"],
    ["create a role", "create role rogue"],
  ])("refuses %s", async (_label, sql) => {
    expect(await errorCode(agent, sql)).toBe("42501");
  });

  it("left the marker person untouched", async () => {
    const { rows } = await admin.query("select given_name from public.people where id = $1", [
      MARKER_PERSON_ID,
    ]);
    expect(rows).toEqual([{ given_name: "LAN-435" }]);
  });
});

describe("the tool's own guard rails", () => {
  it("rejects a second statement smuggled after a semicolon", async () => {
    await expect(
      runInspection(agent, {
        text: `select 1; delete from public.people where id = '${MARKER_PERSON_ID}'`,
      }),
    ).rejects.toMatchObject({ code: "42601" });
  });

  it("runs inside a read-only transaction", async () => {
    // A temporary table needs no grant, so only the transaction mode refuses it.
    await expect(
      runInspection(agent, { text: "create temporary table rogue (id int)" }),
    ).rejects.toMatchObject({ code: "25006" });
  });

  it("refuses a connection that is not the read-only role", async () => {
    await expect(assertInspectorIdentity(admin)).rejects.toThrow(/Refusing/);
  });
});
