-- Corrects `messaging_schedules.invitation_lead_days` to the arithmetic
-- Q-19 actually settled — LAN-171 round 2, OWNER-LAN171-05.
--
-- `20260825120000_messaging_schedule_and_chase.sql` derived every seeded
-- lead as `rsvp_by_days + 3`, on the assumption that the ladder sends three
-- messages after the invitation (two WhatsApp reminders, one email) before
-- the deadline. Brian's round-2 walkthrough resolved the real contradiction
-- in the packet: `REQ-ladder-order` governs over W7's looser "reminders"
-- wording, so `whatsapp_reminder_count` counts the invitation itself as
-- WhatsApp #1. Under that ruling the ladder sends only two messages after
-- the invitation (one WhatsApp reminder, one email) before the deadline, so
-- the lead that lands the last reminder exactly on the deadline is
-- `rsvp_by_days + 2`, not `+ 3`.
--
-- Brian, in the same walkthrough, resolving what the corrected default
-- should be: "the practice default becomes 4 days, and the game and social
-- defaults move by the same arithmetic." Every seeded row shares the same
-- policy shape (cadence 24h, 2 WhatsApp, 1 email), so every type moves by
-- the same one day, not only the three he named.
--
-- This is data, not shape: no column, constraint or default changes, and
-- the application code that reads `whatsapp_reminder_count` as "including
-- the invitation" is already correct (`resolveMessagingPlanIn`,
-- `src/lib/services/messaging-schedule.ts`) — it was the seeded lead that
-- had not caught up. An operator who already edited a row through
-- `/operate/admin/messaging` keeps whatever they set; this only touches
-- rows still holding the original migration's seeded value, so a genuine
-- customisation is never silently overwritten.
update public.messaging_schedules
   set invitation_lead_days = invitation_lead_days - 1
 where invitation_lead_days = rsvp_by_days + 3;
