-- LAN-76 pilot scenario — CLEANUP.
--
-- Removes the events created through the application during the LAN-76 feature
-- test, and nothing else. Run by a human, and — per the retention policy in
-- docs/pilot-data-runbook.md — normally NOT immediately after the test: pilot
-- data is allowed to accumulate so later features can be exercised against
-- earlier ones. Run it when the scenario is no longer useful.
--
-- Safe to run twice: the second run matches nothing and raises nothing.
--
-- Safe to run never: leaving the drafts in place breaks nothing. A draft
-- carries no invitations and distributes nothing — that is invariant P1, and
-- it is the reason this cleanup is low-stakes.
--
-- OWNERSHIP MARKER — sentinel only, and why
--
-- Every other scenario in this directory creates its rows itself, with
-- deterministic primary keys, and deletes by that key qualified by a sentinel.
-- This one cannot: its rows are created by the deployed application, through a
-- browser, and the identifier is generated by PostgreSQL at insert time. The
-- ownership proof is therefore the sentinel `PILOT-LAN-76` in `events.name`,
-- conjoined with a restriction to the three statuses a scenario event can
-- legitimately be in. Both halves are required, and neither is sufficient:
--
--   * the sentinel says the event was created for this test;
--   * the status restriction says it never reached approval — so this file can
--     never delete an approved, occurred, cancelled or rejected event, which
--     is exactly the event that would carry invitations, responses and
--     attendance behind it.
--
-- WHAT THIS SCRIPT WILL NOT DO
--   * It never deletes from auth.users, public.operator_accounts,
--     public.role_assignments, public.roles or public.audit_events. The
--     durable pilot foundation, and the audit history that records who drafted
--     and submitted each event (invariant M2), survive every cleanup. The
--     audit rows deliberately outlive their events — audit_events.entity_id is
--     not a foreign key, precisely so that history is not deletable by
--     removing its subject.
--   * It never deletes an event without the sentinel, whatever its status.
--   * It never widens. Where a foreign row hangs off a scenario event, the
--     preflight aborts with a message rather than removing it — including the
--     cases PostgreSQL would otherwise cascade or null out, enumerated below.
--
-- Anything the preflight does not anticipate is caught by the schema's
-- `on delete restrict` foreign keys: the delete fails, the transaction rolls
-- back, and the scenario is left exactly as it was. Establish actual state
-- with the verification query in README.md before deciding what to do next;
-- never "fix" it by deleting the blocking row.

begin;

-- ---------------------------------------------------------------------------
-- Preflight, part 1 of 2: make the target and the intended deletion reviewable
-- ---------------------------------------------------------------------------
select
  'LAN-76 pilot cleanup — target' as check,
  current_database() as database,
  current_user as connected_as,
  now() as at,
  (
    select count(*) from public.events where name like '%PILOT-LAN-76%'
  ) as scenario_events,
  (
    select count(*) from public.events
     where name like '%PILOT-LAN-76%'
       and status in ('draft', 'pending_approval', 'withdrawn')
  ) as scenario_events_this_script_would_delete,
  (select count(*) from public.events) as event_rows_before,
  (select count(*) from public.audit_events) as audit_rows_before,
  (select count(*) from public.operator_accounts) as operator_account_rows_before;

-- ---------------------------------------------------------------------------
-- Preflight, part 2 of 2: refuse rather than widen
-- ---------------------------------------------------------------------------
do $preflight$
begin
  -- (a) The table this script deletes from must exist. A missing one means the
  --     schema is not what this script was written against.
  if to_regclass('public.events') is null then
    raise exception 'LAN-76 pilot cleanup refused: the expected schema is not present.';
  end if;

  -- (b) Ownership, second half. A scenario event that has reached approval is
  --     no longer a draft nobody depends on: it has an audience, invitations
  --     and possibly attendance behind it. This script does not delete it, and
  --     says so rather than silently leaving it and reporting success.
  if exists (
    select 1 from public.events
     where name like '%PILOT-LAN-76%'
       and status not in ('draft', 'pending_approval', 'withdrawn')
  ) then
    raise exception 'LAN-76 pilot cleanup refused: a PILOT-LAN-76 event has passed approval. An approved, occurred, cancelled or rejected event is never removed by a scenario cleanup.';
  end if;

  -- (c) Rows PostgreSQL would remove WITHOUT being asked. Both `on delete
  --     cascade` foreign keys pointing at public.events are listed here. A
  --     LAN-76 scenario event has neither, so any that exist mean the event
  --     stopped being a scenario event.
  if exists (
    select 1 from public.event_audience_members a
     join public.events e on e.id = a.event_id
     where e.name like '%PILOT-LAN-76%'
  ) then
    raise exception 'LAN-76 pilot cleanup refused: event_audience_members rows hang off a scenario event and would be cascade-deleted.';
  end if;

  if exists (
    select 1 from public.event_questions q
     join public.events e on e.id = q.event_id
     where e.name like '%PILOT-LAN-76%'
  ) then
    raise exception 'LAN-76 pilot cleanup refused: event_questions rows hang off a scenario event and would be cascade-deleted.';
  end if;

  -- (d) Rows PostgreSQL would silently null out. The staging check is nested
  --     rather than combined with `and`: plpgsql plans each statement when it
  --     is first reached, so a nested `if` is genuinely skipped when the
  --     staging schema is absent, while one combined boolean expression would
  --     be planned — and fail — either way.
  if to_regclass('staging.legacy_event_rows') is not null then
    if exists (
      select 1 from staging.legacy_event_rows l
       join public.events e on e.id = l.normalised_event_id
       where e.name like '%PILOT-LAN-76%'
    ) then
      raise exception 'LAN-76 pilot cleanup refused: staging.legacy_event_rows reference a scenario event and would be silently nulled.';
    end if;
  end if;

  -- (e) Containment. These would each be blocked by a foreign key anyway;
  --     naming them turns a foreign-key error into an instruction.
  --
  --     `invitations` and `attendance_records` are deliberately NOT checked
  --     here, and their absence is not an oversight. Both are pinned by
  --     composite foreign key to an event status this delete already excludes —
  --     an invitation requires `approved`, `occurred`, `not_held` or
  --     `cancelled` (invariant P1) and an attendance record requires `occurred`
  --     (invariant P5) — so an event carrying either is caught by guard (b)
  --     above, one check earlier. A guard here could never fire, and an
  --     unreachable guard is worse than none: it reads as protection while
  --     proving nothing, and no test can show it still works.
  if exists (
    select 1 from public.notification_jobs j
     join public.events e on e.id = j.event_id
     where e.name like '%PILOT-LAN-76%'
  ) then
    raise exception 'LAN-76 pilot cleanup refused: notification jobs exist against a scenario event. Nothing should ever have been queued for a draft.';
  end if;

  if exists (
    select 1 from public.schedule_changes c
     join public.events e on e.id = c.event_id
     where e.name like '%PILOT-LAN-76%'
  ) then
    raise exception 'LAN-76 pilot cleanup refused: schedule changes are recorded against a scenario event. That history is evidence (invariant E2) and is not removed here.';
  end if;

  if exists (
    select 1 from public.follow_up_actions f
     join public.events e on e.id = f.subject_event_id
     where e.name like '%PILOT-LAN-76%'
  ) then
    raise exception 'LAN-76 pilot cleanup refused: a follow-up action names a scenario event.';
  end if;

  raise notice 'LAN-76 pilot cleanup: preflight passed on database %.', current_database();
end
$preflight$;

-- ---------------------------------------------------------------------------
-- The deletion
-- ---------------------------------------------------------------------------
-- One statement, because the scenario is one table. Both halves of the
-- ownership marker are conjoined: the sentinel, and the restriction to the
-- statuses a scenario event can be in. Dropping either half is the whole
-- distance between this delete and an arbitrary one.
--
-- The audit rows describing these events are deliberately left behind.

delete from public.events
 where name like '%PILOT-LAN-76%'
   and status in ('draft', 'pending_approval', 'withdrawn');

-- ---------------------------------------------------------------------------
-- Verification — read this before you commit
-- ---------------------------------------------------------------------------
-- Expect zero scenario events, and every durable count unchanged from the
-- preflight above.
select
  'LAN-76 pilot cleanup — result' as check,
  (
    select count(*) from public.events where name like '%PILOT-LAN-76%'
  ) as scenario_events_remaining,
  (select count(*) from public.events) as event_rows_after;

select
  'durable foundation — must be unchanged' as check,
  (select count(*) from auth.users) as auth_users,
  (select count(*) from public.operator_accounts) as operator_accounts,
  (select count(*) from public.role_assignments) as role_assignments,
  (select count(*) from public.audit_events) as audit_events;

commit;
