// W3-01 — What a flipped recruit's record looks like the moment they land.
//
// This screen is a photograph on both sides of a person who really is a flipped
// recruit: a `recruitment_prospects` row at `joined`, pointing at a real
// `season_memberships` row at `onboarding` through `converted_membership_id`,
// with the seven onboarding items the checklist generates and a
// `season_messaging_consents` row granted at the door on 14 August.
//
// An earlier draft proposed all of that onto a long-seeded player's record
// instead, and the result argued with itself in four places: sixty rows of club
// attendance under a status history that said they joined that morning, a
// season confirmed in April, items completed on 30 April, and the page heading
// still carrying the other person's name. Seeding the real thing removed every
// one of those contradictions rather than papering over them.
//
// So this proposal marks; it barely changes anything.
selectRosterNav();

const cardTitled = (pattern) =>
  $$(".MuiPaper-root").find((card) => new RegExp(pattern, "i").test(card.textContent));

// 1 — what arrived pre-filled from the recruit door and questionnaire A.
mark(must(cardTitled("^\\s*PERSON"), "the record has no PERSON card"), 1);

// 2 — and the four recruitment never asks, which onboarding asks of everyone.
const person = cardTitled("^\\s*PERSON");
const blank = $$("tr, div", person).find((row) => {
  const first = row.children?.[0];
  return first && /^\s*Date of birth\s*$/i.test(first.textContent ?? "");
});
if (blank) mark(blank, 2);

// 3 — the checklist, generated by the flip's own transaction. Seven real rows.
const onboarding = cardTitled("subscription invoiced");
if (onboarding) mark(onboarding, 3);

// 4 — the season card, showing onboarding and the date the flip committed.
const season = cardTitled("SEASON ·");
if (season) mark(season, 4);

await settle();
